### ISSUE TITLE
ImportError: cannot import name 'client'

### ISSUE THREAD

**Issue by ewinge** [sina-al/pynlp#1]
I have installed this package with pip3.
There seems to be a circular dependency between the modules.
I get the following exception:

    Traceback (most recent call last):
      File "SemEval-2013.py", line 12, in <module>
        from pynlp import StanfordCoreNLP
      File "/inf/pynlp/pynlp/__init__.py", line 1, in <module>
        from .client import stanford_core_nlp
      File "/inf/pynlp/pynlp/client.py", line 5, in <module>
        from pynlp.wrapper import Document
      File "/inf/pynlp/pynlp/wrapper.py", line 2, in <module>
        from pynlp import client
    ImportError: cannot import name 'client'

**Comment by sina-al** [comment]
Hi ewinge
Thanks for this issue. I've temporarily resolved this.
