### ISSUE TITLE
typo error on StanfordCoreNLP __init__

### ISSUE THREAD

**Issue by avelino** [sina-al/pynlp#20]
```
Traceback (most recent call last):
  File "main_core.py", line 3, in <module>
    from pynlp import StanfordCoreNLP
  File "/Users/avelino/.virtualenvs/nuveo.nlp/lib/python2.7/site-packages/pynlp/__init__.py", line 1, in <module>
    from .client import StanfordCoreNLP
  File "/Users/avelino/.virtualenvs/nuveo.nlp/lib/python2.7/site-packages/pynlp/client.py", line 66
    def __init__(self, properties: Properties):
                                 ^
SyntaxError: invalid syntax
```
https://github.com/sina-al/pynlp/blob/80a235f86953cb7e9050e76ee7878582eb49b988/pynlp/client.py#L66

**Comment by sina-al** [comment]
`pynlp` currently only works with python3
